import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from "../../public/images/profile/developer-pic-1.PNG"
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import LinkArrow from '@/components/Icons'
import HireMe from '@/components/HireMe'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
     <main className='flex items-center text-dark w-full'>
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'>
              <div className='w-1/2'>
                  <Image
                  // style={{height:400,width:400}} 
                   src={profilePic} alt='Madu Frank' className='w-full h-auto'/>
              </div>
              <div className='w-1/2 flex flex-col items-center self-center'>
                <AnimatedText text="Turning your tech visions into reality." className='!text-6xl !text-left'/>
                <p className='my-4 text-base font-medium px-2'>
                   as a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
                </p>
                <div className='flex items-center self-start mt-2 mx-2'>
                  <Link className='flex items-center bg-dark text-white p-2.5 px-6 rounded-lg text-lg font-semibold
                                    hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark'
                    href="/resumepdf" target='_blank'
                    download={true}
                    >Resume 
                  </Link>
                  <Link className='ml-4 text-lg font-medium capitalize text-dark underline'
                   href="/resumepdf" target='_blank'>Contact</Link>
                </div>
              </div>
          </div>
        </Layout>
        <HireMe />
        <div className='absolute right-8 bottom-8 inline-block w-24'>
        <Image src={lightBulb} alt='Madu Frank' className='w-full' h-auto />
        </div>
     </main>
    </>
  )
}
